/**
 * Made with Wonder
 * https://app.wonder.so/user-72d412/files/019f146d-ddcb-7bb6-836c-44b0a56ceb9a/branches/main/pages/019f146e-89cb-7438-be10-59793d34be78?nodeId=019f146e-988b-715c-a24c-0af9db278624
 * Jun 29, 2026
 */
export default function () {
  return (
    <>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&family=JetBrains+Mono:wght@400&display=swap" rel="stylesheet" />
      <style>{"* { box-sizing: border-box; }"}</style>
      <div style={{ display: 'flex', width: '1280px', height: 'fit-content', overflowX: 'clip', overflowY: 'clip', contain: 'content', flexDirection: 'column', backgroundColor: '#ffffff', fontFamily: 'Inter' }}>
        <div style={{ display: 'flex', width: '100%', height: '68px', contain: 'layout', flexShrink: '0', justifyContent: 'space-between', alignItems: 'center', paddingTop: '0px', paddingRight: '40px', paddingBottom: '0px', paddingLeft: '40px', backgroundColor: '#ffffff', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: '#e5e5e5' }}>
          <div style={{ display: 'flex', contain: 'layout', alignItems: 'center', rowGap: '8px', columnGap: '8px' }}>
            <div style={{ display: 'flex', width: '26px', height: '26px', contain: 'layout', flexShrink: '0', justifyContent: 'center', alignItems: 'center', backgroundColor: '#ff4c1e', borderTopLeftRadius: '6px', borderTopRightRadius: '6px', borderBottomRightRadius: '6px', borderBottomLeftRadius: '6px' }}>
              <div style={{ contain: 'layout', color: '#ffffff', fontFamily: '"Plus Jakarta Sans"', fontSize: '16px', fontWeight: '800', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>A</div>
            </div>
            <div style={{ contain: 'layout', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '19px', fontWeight: '800', lineHeight: '1.5', letterSpacing: '-0.475px', display: 'inline-block', overflowWrap: 'normal' }}>analisia</div>
          </div>
          <div style={{ display: 'flex', width: '280px', height: '40px', contain: 'layout', alignItems: 'center', rowGap: '10px', columnGap: '10px', paddingTop: '0px', paddingRight: '14px', paddingBottom: '0px', paddingLeft: '14px', backgroundColor: '#ffffff', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: '#e5e5e5', borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: '#e5e5e5', borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: '#e5e5e5', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', borderBottomRightRadius: '4px', borderBottomLeftRadius: '4px' }}>
            <div style={{ display: 'flex', width: '16px', height: '16px', contain: 'layout', flexDirection: 'column', flexShrink: '0', color: '#666666' }}>
              <svg stroke="rgb(102, 102, 102)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(102, 102, 102)"><circle cx="11" cy="11" r="8" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></circle><line x1="21" y1="21" x2="16.65" y2="16.65" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line></svg>
            </div>
            <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Search articles…</div>
          </div>
        </div>
        <div style={{ display: 'flex', width: '100%', height: 'fit-content', contain: 'layout', flexDirection: 'column', alignItems: 'center', rowGap: '18px', columnGap: '18px', paddingTop: '64px', paddingRight: '40px', paddingBottom: '44px', paddingLeft: '40px' }}>
          <div style={{ display: 'flex', width: '100%', maxWidth: '680px', contain: 'layout', alignItems: 'center', rowGap: '8px', columnGap: '8px' }}>
            <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Blog</div>
            <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>/</div>
            <div style={{ contain: 'layout', color: '#ff4c1e', fontFamily: 'Inter', fontSize: '13px', fontWeight: '600', lineHeight: '1.5', letterSpacing: '0.325px', textTransform: 'uppercase', display: 'inline-block', overflowWrap: 'normal' }}>Guides</div>
          </div>
          <div style={{ width: '100%', maxWidth: '680px', contain: 'layout', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '44px', fontWeight: '800', lineHeight: '1.12', letterSpacing: '-1.1px', display: 'inline-block', overflowWrap: 'normal' }}>The 2026 Playbook for Lowering Google Ads CPA Without Cutting Spend</div>
          <div style={{ width: '100%', maxWidth: '680px', contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '19px', lineHeight: '1.6', display: 'inline-block', overflowWrap: 'normal' }}>A field-tested framework for squeezing more conversions out of the same budget — from bidding signals to landing-page velocity.</div>
          <div style={{ display: 'flex', width: '100%', maxWidth: '680px', contain: 'layout', alignItems: 'center', rowGap: '14px', columnGap: '14px', paddingTop: '6px', paddingRight: '0px', paddingBottom: '0px', paddingLeft: '0px' }}>
            <div style={{ display: 'flex', width: '40px', height: '40px', contain: 'layout', flexShrink: '0', justifyContent: 'center', alignItems: 'center', backgroundColor: '#ff4c1e', borderTopLeftRadius: '9999px', borderTopRightRadius: '9999px', borderBottomRightRadius: '9999px', borderBottomLeftRadius: '9999px' }}>
              <div style={{ contain: 'layout', color: '#ffffff', fontFamily: 'Inter', fontSize: '14px', fontWeight: '700', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>MR</div>
            </div>
            <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', rowGap: '2px', columnGap: '2px' }}>
              <div style={{ contain: 'layout', color: '#111111', fontFamily: 'Inter', fontSize: '14px', fontWeight: '600', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Maya Reinhardt</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '12px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Head of Paid Media</div>
            </div>
            <div style={{ display: 'flex', width: '1px', height: '28px', contain: 'layout', flexDirection: 'column', flexShrink: '0', marginTop: '0px', marginRight: '6px', marginBottom: '0px', marginLeft: '6px', backgroundColor: '#e5e5e5' }}></div>
            <div style={{ display: 'flex', contain: 'layout', alignItems: 'center', rowGap: '6px', columnGap: '6px' }}>
              <div style={{ display: 'flex', width: '14px', height: '14px', contain: 'layout', flexDirection: 'column', flexShrink: '0', color: '#666666' }}>
                <svg stroke="rgb(102, 102, 102)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(102, 102, 102)"><rect x="3" y="4" width="18" height="18" rx="2" ry="2" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></rect><line x1="16" y1="2" x2="16" y2="6" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line><line x1="8" y1="2" x2="8" y2="6" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line><line x1="3" y1="10" x2="21" y2="10" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line></svg>
              </div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Jun 28, 2026</div>
            </div>
            <div style={{ display: 'flex', contain: 'layout', alignItems: 'center', rowGap: '6px', columnGap: '6px' }}>
              <div style={{ display: 'flex', width: '14px', height: '14px', contain: 'layout', flexDirection: 'column', flexShrink: '0', color: '#666666' }}>
                <svg stroke="rgb(102, 102, 102)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(102, 102, 102)"><circle cx="12" cy="12" r="10" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></circle><polyline points="12 6 12 12 16 14" color="rgb(102, 102, 102)" fill="none" stroke="rgb(102, 102, 102)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></polyline></svg>
              </div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>8 min read</div>
            </div>
          </div>
        </div>
        <div style={{ display: 'flex', position: 'relative', width: '100%', height: 'fit-content', contain: 'layout', justifyContent: 'center', rowGap: '60px', paddingTop: '0px', paddingRight: '40px', paddingBottom: '72px', paddingLeft: '40px' }}>
          <div style={{ display: 'flex', position: 'absolute', width: '260px', height: 'fit-content', contain: 'layout', flexDirection: 'column', flexShrink: '0', rowGap: '14px', columnGap: '14px', left: '40px', top: '0px', paddingTop: '6px', paddingRight: '0px', paddingBottom: '0px', paddingLeft: '0px' }}>
            <div style={{ contain: 'layout', paddingTop: '0px', paddingRight: '0px', paddingBottom: '4px', paddingLeft: '0px', color: '#666666', fontFamily: 'Inter', fontSize: '11px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '1.1px', textTransform: 'uppercase', display: 'inline-block', overflowWrap: 'normal' }}>On this page</div>
            <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#e5e5e5' }}>
              <div style={{ display: 'flex', contain: 'layout', marginTop: '0px', marginRight: '0px', marginBottom: '0px', marginLeft: '-2px', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#ff4c1e' }}>
                <div style={{ contain: 'layout', paddingTop: '7px', paddingRight: '0px', paddingBottom: '7px', paddingLeft: '14px', color: '#ff4c1e', fontFamily: 'Inter', fontSize: '13px', fontWeight: '600', lineHeight: '1.4', display: 'inline-block', overflowWrap: 'normal' }}>Why CPA creeps up over time</div>
              </div>
              <div style={{ display: 'flex', contain: 'layout', marginTop: '0px', marginRight: '0px', marginBottom: '0px', marginLeft: '-2px', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#00000000' }}>
                <div style={{ contain: 'layout', paddingTop: '7px', paddingRight: '0px', paddingBottom: '7px', paddingLeft: '14px', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.4', display: 'inline-block', overflowWrap: 'normal' }}>Auditing your bidding signals</div>
              </div>
              <div style={{ display: 'flex', contain: 'layout', marginTop: '0px', marginRight: '0px', marginBottom: '0px', marginLeft: '-2px', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#00000000' }}>
                <div style={{ contain: 'layout', paddingTop: '7px', paddingRight: '0px', paddingBottom: '7px', paddingLeft: '24px', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.4', display: 'inline-block', overflowWrap: 'normal' }}>Value-based bidding setup</div>
              </div>
              <div style={{ display: 'flex', contain: 'layout', marginTop: '0px', marginRight: '0px', marginBottom: '0px', marginLeft: '-2px', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#00000000' }}>
                <div style={{ contain: 'layout', paddingTop: '7px', paddingRight: '0px', paddingBottom: '7px', paddingLeft: '14px', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.4', display: 'inline-block', overflowWrap: 'normal' }}>Landing-page velocity wins</div>
              </div>
              <div style={{ display: 'flex', contain: 'layout', marginTop: '0px', marginRight: '0px', marginBottom: '0px', marginLeft: '-2px', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#00000000' }}>
                <div style={{ contain: 'layout', paddingTop: '7px', paddingRight: '0px', paddingBottom: '7px', paddingLeft: '14px', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.4', display: 'inline-block', overflowWrap: 'normal' }}>Creative testing cadence</div>
              </div>
              <div style={{ display: 'flex', contain: 'layout', marginTop: '0px', marginRight: '0px', marginBottom: '0px', marginLeft: '-2px', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#00000000' }}>
                <div style={{ contain: 'layout', paddingTop: '7px', paddingRight: '0px', paddingBottom: '7px', paddingLeft: '14px', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.4', display: 'inline-block', overflowWrap: 'normal' }}>Measuring incremental lift</div>
              </div>
              <div style={{ display: 'flex', contain: 'layout', marginTop: '0px', marginRight: '0px', marginBottom: '0px', marginLeft: '-2px', borderLeftWidth: '2px', borderLeftStyle: 'solid', borderLeftColor: '#00000000' }}>
                <div style={{ contain: 'layout', paddingTop: '7px', paddingRight: '0px', paddingBottom: '7px', paddingLeft: '14px', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.4', display: 'inline-block', overflowWrap: 'normal' }}>The weekly optimization loop</div>
              </div>
            </div>
            <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', rowGap: '10px', columnGap: '10px', paddingTop: '20px', paddingRight: '0px', paddingBottom: '0px', paddingLeft: '0px', marginTop: '8px', marginRight: '0px', marginBottom: '0px', marginLeft: '0px', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5' }}>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '11px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '1.1px', textTransform: 'uppercase', display: 'inline-block', overflowWrap: 'normal' }}>Share</div>
              <div style={{ display: 'flex', contain: 'layout', rowGap: '8px', columnGap: '8px' }}>
                <div style={{ display: 'flex', width: '34px', height: '34px', contain: 'layout', justifyContent: 'center', alignItems: 'center', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: '#e5e5e5', borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: '#e5e5e5', borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: '#e5e5e5', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', borderBottomRightRadius: '4px', borderBottomLeftRadius: '4px' }}>
                  <div style={{ display: 'flex', width: '15px', height: '15px', contain: 'layout', flexDirection: 'column', color: '#111111' }}>
                    <svg stroke="rgb(17, 17, 17)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(17, 17, 17)"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path></svg>
                  </div>
                </div>
                <div style={{ display: 'flex', width: '34px', height: '34px', contain: 'layout', justifyContent: 'center', alignItems: 'center', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: '#e5e5e5', borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: '#e5e5e5', borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: '#e5e5e5', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', borderBottomRightRadius: '4px', borderBottomLeftRadius: '4px' }}>
                  <div style={{ display: 'flex', width: '15px', height: '15px', contain: 'layout', flexDirection: 'column', color: '#111111' }}>
                    <svg stroke="rgb(17, 17, 17)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(17, 17, 17)"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path><rect x="2" y="9" width="4" height="12" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></rect><circle cx="4" cy="4" r="2" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></circle></svg>
                  </div>
                </div>
                <div style={{ display: 'flex', width: '34px', height: '34px', contain: 'layout', justifyContent: 'center', alignItems: 'center', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: '#e5e5e5', borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: '#e5e5e5', borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: '#e5e5e5', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', borderBottomRightRadius: '4px', borderBottomLeftRadius: '4px' }}>
                  <div style={{ display: 'flex', width: '15px', height: '15px', contain: 'layout', flexDirection: 'column', color: '#111111' }}>
                    <svg stroke="rgb(17, 17, 17)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(17, 17, 17)"><path d="M15 7h3a5 5 0 0 1 5 5 5 5 0 0 1-5 5h-3m-6 0H6a5 5 0 0 1-5-5 5 5 0 0 1 5-5h3" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path><line x1="8" y1="12" x2="16" y2="12" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line></svg>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', position: 'relative', width: '680px', height: 'fit-content', contain: 'layout', flexDirection: 'column', flexShrink: '0' }}>
            <div style={{ display: 'flex', width: '100%', height: '380px', contain: 'layout', flexDirection: 'column', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '40px', marginLeft: '0px', backgroundImage: 'url("https://cdn.wonder.so/images/019f1454-2c02-7635-a590-195bee5ccf5e/f96e460cd7bdf82317739647f551e5fed4416d0ebdc20dbf3f1fba91b9f1c6d8.jpg")', backgroundSize: 'cover', backgroundRepeat: 'no-repeat', backgroundPositionX: 'center', backgroundPositionY: 'center', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderBottomRightRadius: '8px', borderBottomLeftRadius: '8px' }}></div>
            <div style={{ height: '42px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '16px', marginLeft: '0px', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '28px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '-0.7px', display: 'inline-block', overflowWrap: 'normal' }}>Why CPA creeps up over time</div>
            <div style={{ height: '158px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '24px', marginLeft: '0px', color: '#111111', fontFamily: 'Inter', fontSize: '18px', lineHeight: '1.75', display: 'inline-block', overflowWrap: 'normal' }}>Cost per acquisition rarely spikes overnight. It drifts — a few cents here, a percentage point there — until the account that hit a 3.2x ROAS last quarter is quietly running at break-even. The usual reflex is to slash budget, but that often starves the algorithm of the conversion volume it needs to optimize, making the problem worse.</div>
            <div style={{ height: '95px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '28px', marginLeft: '0px', color: '#111111', fontFamily: 'Inter', fontSize: '18px', lineHeight: '1.75', display: 'inline-block', overflowWrap: 'normal' }}>This playbook walks through the seven levers we pull, in order, before we ever touch the budget dial. Each one is independent, measurable, and reversible — so you can ship them one at a time and read the impact cleanly.</div>
            <div style={{ display: 'flex', height: '72px', contain: 'layout', flexDirection: 'column', flexShrink: '0', paddingTop: '4px', paddingRight: '0px', paddingBottom: '4px', paddingLeft: '24px', marginTop: '0px', marginRight: '0px', marginBottom: '32px', marginLeft: '0px', borderLeftWidth: '3px', borderLeftStyle: 'solid', borderLeftColor: '#ff4c1e' }}>
              <div style={{ contain: 'layout', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '22px', fontWeight: '600', lineHeight: '1.45', display: 'inline-block', overflowWrap: 'normal' }}>“Budget is the last lever you should pull, not the first. Signal quality moves CPA further than spend ever will.”</div>
            </div>
            <div style={{ height: '42px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '16px', marginLeft: '0px', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '28px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '-0.7px', display: 'inline-block', overflowWrap: 'normal' }}>Auditing your bidding signals</div>
            <div style={{ height: '126px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '24px', marginLeft: '0px', color: '#111111', fontFamily: 'Inter', fontSize: '18px', lineHeight: '1.75', display: 'inline-block', overflowWrap: 'normal' }}>Smart Bidding is only as good as the signals you feed it. Start by confirming that your conversion actions reflect real business value — not just form fills. A lead that closes at 12% should not be weighted the same as one that closes at 47%.</div>
            <div style={{ display: 'flex', width: '100%', height: '84px', contain: 'layout', flexWrap: 'wrap', flexShrink: '0', columnGap: '4px', paddingTop: '18px', paddingRight: '22px', paddingBottom: '18px', paddingLeft: '22px', marginTop: '0px', marginRight: '0px', marginBottom: '28px', marginLeft: '0px', backgroundColor: '#111111', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderBottomRightRadius: '8px', borderBottomLeftRadius: '8px' }}>
              <div style={{ contain: 'layout', color: '#ff4c1e', fontFamily: '"JetBrains Mono"', fontSize: '14px', lineHeight: '1.7', display: 'inline-block', overflowWrap: 'normal' }}>// value-based conversion import</div>
              <div style={{ contain: 'layout', color: '#ffffff', fontFamily: '"JetBrains Mono"', fontSize: '14px', lineHeight: '1.7', display: 'inline-block', overflowWrap: 'normal' }}>conversions.upload(value=lead.expected_revenue)</div>
            </div>
            <div style={{ height: '126px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '24px', marginLeft: '0px', color: '#111111', fontFamily: 'Inter', fontSize: '18px', lineHeight: '1.75', display: 'inline-block', overflowWrap: 'normal' }}>Once value-based conversions are flowing, switch the campaign to Maximize Conversion Value with a target ROAS. Give it 14 days and at least 30 conversions before judging performance — the model needs runway to recalibrate.</div>
            <div style={{ height: '32px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '14px', marginLeft: '0px', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '21px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '-0.525px', display: 'inline-block', overflowWrap: 'normal' }}>Value-based bidding setup</div>
            <div style={{ height: '95px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '28px', marginLeft: '0px', color: '#111111', fontFamily: 'Inter', fontSize: '18px', lineHeight: '1.75', display: 'inline-block', overflowWrap: 'normal' }}>Map each conversion action to a revenue proxy, exclude junk actions from the bidding set, and confirm the data is landing in the right column before you flip the switch. Small setup errors here compound fast.</div>
            <div style={{ display: 'flex', width: '100%', height: '221px', contain: 'layout', flexDirection: 'column', flexShrink: '0', rowGap: '18px', columnGap: '18px', paddingTop: '34px', paddingRight: '36px', paddingBottom: '34px', paddingLeft: '36px', marginTop: '12px', marginRight: '0px', marginBottom: '12px', marginLeft: '0px', backgroundColor: '#111111', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderBottomRightRadius: '8px', borderBottomLeftRadius: '8px' }}>
              <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', rowGap: '8px', columnGap: '8px' }}>
                <div style={{ contain: 'layout', color: '#ffffff', fontFamily: '"Plus Jakarta Sans"', fontSize: '24px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '-0.6px', display: 'inline-block', overflowWrap: 'normal' }}>Get the weekly performance digest</div>
                <div style={{ contain: 'layout', color: '#999999', fontFamily: 'Inter', fontSize: '15px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>One email every Tuesday. Tactical breakdowns like this one — no fluff. Join 12,400 marketers.</div>
              </div>
              <div style={{ display: 'flex', contain: 'layout', rowGap: '10px', columnGap: '10px' }}>
                <div style={{ display: 'flex', height: '46px', contain: 'layout', alignItems: 'center', paddingTop: '0px', paddingRight: '16px', paddingBottom: '0px', paddingLeft: '16px', backgroundColor: '#ffffff', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', borderBottomRightRadius: '4px', borderBottomLeftRadius: '4px', flex: '1 1 0%' }}>
                  <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '15px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>you@company.com</div>
                </div>
                <div style={{ display: 'flex', height: '46px', contain: 'layout', flexShrink: '0', alignItems: 'center', rowGap: '8px', columnGap: '8px', paddingTop: '0px', paddingRight: '24px', paddingBottom: '0px', paddingLeft: '24px', backgroundColor: '#ff4c1e', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', borderBottomRightRadius: '4px', borderBottomLeftRadius: '4px' }}>
                  <div style={{ contain: 'layout', color: '#ffffff', fontFamily: 'Inter', fontSize: '15px', fontWeight: '600', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Subscribe</div>
                  <div style={{ display: 'flex', width: '16px', height: '16px', contain: 'layout', flexDirection: 'column', color: '#ffffff' }}>
                    <svg stroke="rgb(255, 255, 255)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(255, 255, 255)"><line x1="5" y1="12" x2="19" y2="12" color="rgb(255, 255, 255)" fill="none" stroke="rgb(255, 255, 255)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line><polyline points="12 5 19 12 12 19" color="rgb(255, 255, 255)" fill="none" stroke="rgb(255, 255, 255)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></polyline></svg>
                  </div>
                </div>
              </div>
            </div>
            <div style={{ height: '42px', contain: 'layout', flexShrink: '0', marginTop: '16px', marginRight: '0px', marginBottom: '16px', marginLeft: '0px', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '28px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '-0.7px', display: 'inline-block', overflowWrap: 'normal' }}>Landing-page velocity wins</div>
            <div style={{ height: '95px', contain: 'layout', flexShrink: '0', marginTop: '0px', marginRight: '0px', marginBottom: '24px', marginLeft: '0px', color: '#111111', fontFamily: 'Inter', fontSize: '18px', lineHeight: '1.75', display: 'inline-block', overflowWrap: 'normal' }}>A 100 ms improvement in LCP routinely lifts conversion rate by 1–2%. Because CPA is downstream of conversion rate, speed work is some of the highest-leverage optimization you can do — and it never gets undone by an auction.</div>
            <div style={{ height: '95px', contain: 'layout', flexShrink: '0', color: '#111111', fontFamily: 'Inter', fontSize: '18px', lineHeight: '1.75', display: 'inline-block', overflowWrap: 'normal' }}>Compress hero imagery, defer third-party tags, and inline critical CSS. Then re-test on a throttled mobile connection, because that is where most of your paid traffic actually lands.</div>
          </div>
        </div>
        <div style={{ display: 'flex', width: '100%', maxWidth: '1000px', height: 'fit-content', contain: 'layout', flexDirection: 'column', rowGap: '20px', columnGap: '20px', paddingTop: '44px', paddingRight: '40px', paddingBottom: '64px', paddingLeft: '40px', marginTop: '0px', marginRight: 'auto', marginBottom: '0px', marginLeft: 'auto', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5' }}>
          <div style={{ contain: 'layout', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '24px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '-0.6px', display: 'inline-block', overflowWrap: 'normal' }}>Read next in Guides</div>
          <div style={{ display: 'flex', contain: 'layout', rowGap: '24px', columnGap: '24px' }}>
            <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', rowGap: '12px', columnGap: '12px', paddingTop: '24px', paddingRight: '24px', paddingBottom: '24px', paddingLeft: '24px', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: '#e5e5e5', borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: '#e5e5e5', borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: '#e5e5e5', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderBottomRightRadius: '8px', borderBottomLeftRadius: '8px', flex: '1 1 0%' }}>
              <div style={{ contain: 'layout', color: '#ff4c1e', fontFamily: 'Inter', fontSize: '12px', fontWeight: '600', lineHeight: '1.5', letterSpacing: '0.3px', textTransform: 'uppercase', display: 'inline-block', overflowWrap: 'normal' }}>Analytics</div>
              <div style={{ contain: 'layout', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '19px', fontWeight: '700', lineHeight: '1.3', display: 'inline-block', overflowWrap: 'normal' }}>Server-side tagging: the setup that fixed our attribution gap</div>
              <div style={{ display: 'flex', contain: 'layout', alignItems: 'center', rowGap: '8px', columnGap: '8px', marginTop: '4px', marginRight: '0px', marginBottom: '0px', marginLeft: '0px' }}>
                <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>9 min read</div>
                <div style={{ display: 'flex', width: '15px', height: '15px', contain: 'layout', flexDirection: 'column', color: '#111111' }}>
                  <svg stroke="rgb(17, 17, 17)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(17, 17, 17)"><line x1="7" y1="17" x2="17" y2="7" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line><polyline points="7 7 17 7 17 17" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></polyline></svg>
                </div>
              </div>
            </div>
            <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', rowGap: '12px', columnGap: '12px', paddingTop: '24px', paddingRight: '24px', paddingBottom: '24px', paddingLeft: '24px', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: '#e5e5e5', borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: '#e5e5e5', borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: '#e5e5e5', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderBottomRightRadius: '8px', borderBottomLeftRadius: '8px', flex: '1 1 0%' }}>
              <div style={{ contain: 'layout', color: '#ff4c1e', fontFamily: 'Inter', fontSize: '12px', fontWeight: '600', lineHeight: '1.5', letterSpacing: '0.3px', textTransform: 'uppercase', display: 'inline-block', overflowWrap: 'normal' }}>Guides</div>
              <div style={{ contain: 'layout', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '19px', fontWeight: '700', lineHeight: '1.3', display: 'inline-block', overflowWrap: 'normal' }}>How to structure a profitable Performance Max campaign in 2026</div>
              <div style={{ display: 'flex', contain: 'layout', alignItems: 'center', rowGap: '8px', columnGap: '8px', marginTop: '4px', marginRight: '0px', marginBottom: '0px', marginLeft: '0px' }}>
                <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>6 min read</div>
                <div style={{ display: 'flex', width: '15px', height: '15px', contain: 'layout', flexDirection: 'column', color: '#111111' }}>
                  <svg stroke="rgb(17, 17, 17)" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" xmlns="http://www.w3.org/2000/svg" color="rgb(17, 17, 17)"><line x1="7" y1="17" x2="17" y2="7" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line><polyline points="7 7 17 7 17 17" color="rgb(17, 17, 17)" fill="none" stroke="rgb(17, 17, 17)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></polyline></svg>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div style={{ position: 'relative', contain: 'layout' }}></div>
        <div style={{ display: 'flex', width: '100%', maxWidth: '1000px', height: 'fit-content', contain: 'layout', flexShrink: '0', justifyContent: 'space-between', rowGap: '24px', columnGap: '24px', paddingTop: '48px', paddingRight: '40px', paddingBottom: '48px', paddingLeft: '40px', marginTop: '0px', marginRight: 'auto', marginBottom: '0px', marginLeft: 'auto', backgroundColor: '#ffffff', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: '#e5e5e5' }}>
          <div style={{ display: 'flex', width: '320px', contain: 'layout', flexDirection: 'column', rowGap: '12px', columnGap: '12px' }}>
            <div style={{ display: 'flex', contain: 'layout', alignItems: 'center', rowGap: '8px', columnGap: '8px' }}>
              <div style={{ display: 'flex', width: '24px', height: '24px', contain: 'layout', justifyContent: 'center', alignItems: 'center', backgroundColor: '#ff4c1e', borderTopLeftRadius: '6px', borderTopRightRadius: '6px', borderBottomRightRadius: '6px', borderBottomLeftRadius: '6px' }}>
                <div style={{ contain: 'layout', color: '#ffffff', fontFamily: '"Plus Jakarta Sans"', fontSize: '14px', fontWeight: '800', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>A</div>
              </div>
              <div style={{ contain: 'layout', color: '#111111', fontFamily: '"Plus Jakarta Sans"', fontSize: '17px', fontWeight: '800', lineHeight: '1.5', letterSpacing: '-0.425px', display: 'inline-block', overflowWrap: 'normal' }}>analisia</div>
            </div>
            <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.6', display: 'inline-block', overflowWrap: 'normal' }}>Performance marketing, decoded weekly. Tactics from the team running paid media for fast-growing brands.</div>
            <div style={{ contain: 'layout', marginTop: '8px', marginRight: '0px', marginBottom: '0px', marginLeft: '0px', color: '#666666', fontFamily: 'Inter', fontSize: '13px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>© 2026 Analisia. All rights reserved.</div>
          </div>
          <div style={{ display: 'flex', contain: 'layout', justifyContent: 'flex-end', rowGap: '64px', columnGap: '64px' }}>
            <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', rowGap: '12px', columnGap: '12px' }}>
              <div style={{ contain: 'layout', color: '#111111', fontFamily: 'Inter', fontSize: '12px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '1.2px', textTransform: 'uppercase', display: 'inline-block', overflowWrap: 'normal' }}>Explore</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Guides</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Analytics</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Case Studies</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>About</div>
            </div>
            <div style={{ display: 'flex', contain: 'layout', flexDirection: 'column', rowGap: '12px', columnGap: '12px' }}>
              <div style={{ contain: 'layout', color: '#111111', fontFamily: 'Inter', fontSize: '12px', fontWeight: '700', lineHeight: '1.5', letterSpacing: '1.2px', textTransform: 'uppercase', display: 'inline-block', overflowWrap: 'normal' }}>Newsletter</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Subscribe</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>Past issues</div>
              <div style={{ contain: 'layout', color: '#666666', fontFamily: 'Inter', fontSize: '14px', lineHeight: '1.5', display: 'inline-block', overflowWrap: 'normal' }}>RSS feed</div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}